### PR TITLE
Basic home page

### PR DESCRIPTION
**Pull request by dswcodes0**
i need to push my changes to development so i can access them on my other branches

### CODE REVIEW

**Comment by charliegriffinfacebook** [comment]
@dswcodes0 please include a comment with a description of what this feature is and a test plan including a screenshot of this code working.

**Review by charliegriffinfacebook — CHANGES_REQUESTED** [review]
see previous comment

**Comment by dswcodes0** [comment]
>@charliegriffinfacebook this is the unsigned in home html, the user can enter their usernmae email and password: 
Screenshot 2023-07-07 at 11 54 04 AM
there are other commits in this pull request but those commits are meant for the other pull requests, i will address those features in the other pull requests

**Comment by dswcodes0** [comment]
this is actually the image of the unsigned in home, the one i posted before was the sign up, i added links to sign up and sign in here also i added a button to ask the watcher which will later link to the chatbot to ask questions
Screenshot 2023-07-07 at 11 57 48 AM

**Comment by annagaofacebook** [comment]
I'm still having a hard time understanding what exactly is part of this PR. With the code in this PR as is, what should be showing up? Is it both of these screenshots you sent?

In the future, let's try to keep PRs to be just one feature and not include additional partially finished features 🙂

Code itself looks good so far!

**Pull request merged**
