### PR TITLE
made chatbot element and placed it in signedinhome

### PR DESCRIPTION
**Pull request by dswcodes0**

### CODE REVIEW

**Comment by annagaofacebook** [comment]
Hey Darren, can you add a more detailed description as well as at test plan? Basically, what the code does and a screenshot of your website showing the UI

**Comment by dswcodes0** [comment]
i did not add any code to the page, i only removed the hard coded chatbot part in the signed in home portion, put it in its own component and loaded it back into signed in home, nothing visually changed but here is what it looks like: 
Screenshot 2023-07-07 at 12 10 29 PM

**Comment by annagaofacebook** [comment]
Thanks for the test plan and explanation! It makes reading and understanding your code a lot easier for us. Even if nothing has changed visually, it's still a good idea to show that in the test plan.

**Review by annagaofacebook — APPROVED** [review]
Good job for keeping your PR simple and straight to the point. I can clearly see you're re-factoring chatbot to be its own component, which also makes your SignedInHome file easier to read.

**Pull request merged**
